FinalExam/Models/Place.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FinalExam.Models
{
    public class Place
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Desription { get; set; }
        public ApplicationUser ApplicationUser { get; set; }
        public string ApplicationUserId { get; set; }
        public IEnumerable<Report> Reports { get; set; }
        public string ImagePath { get; set; }
        public IEnumerable<ReportImage> Images { get; set; }
        public double AverageRaiting { get; set; }

    }
}

FinalExam/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalExam.Data;
using FinalExam.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using FinalExam.Services;

namespace FinalExam.Controllers
{
    [Authorize]
    public class PlacesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _appEnvironment;
        private readonly FileUploadService _fileUploadService;

        public PlacesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IHostingEnvironment appEnvironment
        , FileUploadService fileUploadService)
        {
            _context = context;
            _userManager = userManager;
            _fileUploadService = fileUploadService;
            _appEnvironment = appEnvironment;
        }

        public async Task<IActionResult> Index(string searchWord, int pageNum=1)
        {
            var plaecs = _context.Places.Include(p => p.ApplicationUser).Include(p=>p.Reports).Include(p=>p.Images);
            if (!string.IsNullOrEmpty(searchWord))
            {
                plaecs = _context.Places.Where(p => p.Name.Contains(searchWord)).Include(p=>p.ApplicationUser).Include(p => p.Reports).Include(p => p.Images);
            }

            IndexViewModel ivm = new IndexViewModel();
            int pageSize = 20;

            var count = plaecs.Count();
            var items = await plaecs.Skip((pageNum - 1) * pageSize).Take(pageSize).ToListAsync();
            PageViewModel pageViewModel = new PageViewModel(count, pageNum, pageSize);

            ivm.PageViewModel = pageViewModel;
            ivm.Places = items;
            
            return View(ivm);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var place = await _context.Places
                .Include(p => p.ApplicationUser)
                .Include(p=>p.Reports)
                .Include(p=>p.Images)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (place == null)
            {
                return NotFound();
            }

            if (place.Reports.Count() != 0)
            {
                place.AverageRaiting = place.Reports.Average(s => s.Raiting);
            }

            return View(place);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Desription,ApplicationUserId,ImagePath,AverageRaiting")] Place place, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    UploadPhoto(place, image);
                }

                place.ApplicationUserId = _userManager.GetUserId(User);
                _context.Add(place);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(place);
        }

        // GET: Places/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var place = await _context.Places.SingleOrDefaultAsync(m => m.Id == id);
            if (place == null)
            {
                return NotFound();
            }

            return View(place);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Desription,ApplicationUserId,ImagePath,AverageRaiting")] Place place)
        {
            if (id != place.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    place.ApplicationUserId = _userManager.GetUserId(User);;
                    _context.Update(place);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlaceExists(place.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(place);
        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var place = await _context.Places
                .Include(p => p.ApplicationUser)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (place == null)
            {
                return NotFound();
            }

            return View(place);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var place = await _context.Places.SingleOrDefaultAsync(m => m.Id == id);
            _context.Places.Remove(place);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlaceExists(int id)
        {
            return _context.Places.Any(e => e.Id == id);
        }
        private void UploadPhoto(Place place, IFormFile image)
        {
            var path = Path.Combine(_appEnvironment.WebRootPath, $"images\\{place.Name}\\image");
            _fileUploadService.Upload(path, image.FileName, image);
            place.ImagePath = $"images/{place.Name}/image/{image.FileName}";
        }
    }
}

FinalExam/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalExam.Data;
using FinalExam.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using System.IO;
using FinalExam.Services;
using Microsoft.AspNetCore.Hosting;

namespace FinalExam.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _appEnvironment;
        private readonly FileUploadService _fileUploadService;

        public ReportsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IHostingEnvironment appEnvironment
        , FileUploadService fileUploadService)
        {
            _context = context;
            _userManager = userManager;
            _fileUploadService = fileUploadService;
            _appEnvironment = appEnvironment;
        }

        // GET: Reports
        public async Task<IActionResult> Index()
        {
            var reports = _context.Reports.Include(r => r.ApplicationUser).Include(r => r.Place);
            return View(await reports.ToListAsync());
        }

        // GET: Reports/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var report = await _context.Reports
                .Include(r => r.ApplicationUser)
                .Include(r => r.Place)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (report == null)
            {
                return NotFound();
            }

            return View(report);
        }


        public IActionResult Create()
        {
            ViewData["PlaceId"] = new SelectList(_context.Places, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string title,int placeId, string description, double raiting)
        {
            Report report = new Report()
            {
                Title = title,
                Description = description,
                Raiting = raiting,
                PlaceId = placeId,
                ApplicationUserId = _userManager.GetUserId(User)
            };
            _context.Add(report);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var report = await _context.Reports.SingleOrDefaultAsync(m => m.Id == id);
            if (report == null)
            {
                return NotFound();
            }

            ViewData["PlaceId"] = new SelectList(_context.Places, "Id", "Id", report.PlaceId);
            return View(report);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,ApplicationUserId,PlaceId,Raiting")] Report report)
        {
            if (id != report.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    report.ApplicationUserId = _userManager.GetUserId(User);
                    _context.Update(report);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReportExists(report.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["PlaceId"] = new SelectList(_context.Places, "Id", "Name", report.PlaceId);
            return View(report);
        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var report = await _context.Reports
                .Include(r => r.ApplicationUser)
                .Include(r => r.Place)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (report == null)
            {
                return NotFound();
            }

            return View(report);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var report = await _context.Reports.SingleOrDefaultAsync(m => m.Id == id);
            _context.Reports.Remove(report);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReportExists(int id)
        {
            return _context.Reports.Any(e => e.Id == id);
        }
        public async Task<IActionResult> AddNewImage(int placeId, string userId, string title, IFormFile image)
        {
            if (image != null)
            {
                ReportImage img = new ReportImage()
                {
                    Title = title,
                    ApplicationUserId = userId,
                    PlaceId = placeId
                };
                UploadPhoto(img, image);
                _context.Images.Add(img);
                _context.SaveChanges();
            }

            
            return RedirectToAction("Index", "Places");
        }
        private void UploadPhoto(ReportImage image, IFormFile img)
        {
            var path = Path.Combine(_appEnvironment.WebRootPath, $"images\\{image.Title}\\image");
            _fileUploadService.Upload(path, img.FileName, img);
            image.ImagePath = $"images/{image.Title}/image/{img.FileName}";
        }
    }
}

FinalExam/Views/Places/Create.cshtml
@model FinalExam.Models.Place

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add new place</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Desription" class="control-label"></label>
                <textarea asp-for="Desription" class="form-control"></textarea> 
                <span asp-validation-for="Desription" class="text-danger"></span>
            </div>
            <div class="custom-file">
                <input name="image" type="file" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalExam/Views/Places/Delete.cshtml
@model FinalExam.Models.Place

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Place</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Desription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Desription)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AverageRaiting)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AverageRaiting)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FinalExam/Views/Places/Details.cshtml
@model FinalExam.Models.Place

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>@Model.Name</h2>

<div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img src="/@Model.ImagePath" class="card-img" alt="..." style="height: 100px; width: 100px;">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">@Model.Name</h5>
                <p class="card-text">@Model.Desription</p>
                <p class="card-text"><small class="text-muted">@Model.AverageRaiting</small></p>
            </div>
        </div>
    </div>
</div>

<h2>Gallery</h2>

@{
    if (Model.Images != null)
    {
        foreach (var img in Model.Images)
        {
            <img src="/@img.ImagePath" style="height: 100px; width: 100px;"/>
        }
    }
}
<h2>Average raiting: @Model.AverageRaiting</h2>
@{
    <h2>Reviews</h2>
    if (Model.Reports != null)
    {
        foreach (var report in Model.Reports)
        {
            <div>Title @report.Title</div>
            <div>Description @report.Description</div>
            <div>Raiting @report.Raiting</div>
        }
    }
}
<h3>Add review</h3>
<div class="row">
<div class="col-md-2">
    @using (Html.BeginForm("Create", "Reports", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input hidden="true" name="placeId" value="@Model.Id" />
        <label>Title</label>
        <input type="text" name="title" />
        <label>Description</label>
        <textarea name="description"></textarea>
        <label>Raiting</label>
        <input type="number" name="raiting" />
        <button>Submit review</button>

    }
</div>
</div>
<h3>Uplaod new Photo</h3>

@using (Html.BeginForm("AddNewImage", "Reports", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input hidden="true" name="placeId" value="@Model.Id" />
    <input hidden="true" type="text" name="title" value="@Model.Name"/>
    <input type="file" name="image" />
    <button>Upload photo</button>

}

FinalExam/Views/Places/Edit.cshtml
@model FinalExam.Models.Place

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Place</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Desription" class="control-label"></label>
                <input asp-for="Desription" class="form-control" />
                <span asp-validation-for="Desription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationUserId" class="control-label"></label>
                <select asp-for="ApplicationUserId" class="form-control" asp-items="ViewBag.ApplicationUserId"></select>
                <span asp-validation-for="ApplicationUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AverageRaiting" class="control-label"></label>
                <input asp-for="AverageRaiting" class="form-control" />
                <span asp-validation-for="AverageRaiting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalExam/Views/Places/Index.cshtml
@model FinalExam.Models.IndexViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>All places</h2>

@{
    <div class="row">
        @foreach (var item in Model.Places)
        {
            <div class="card col-sm-6" style="width: 18rem;">
                <img src="@item.ImagePath" class="card-img-top" alt="..." style="width: 100px" ; height="100px" ;>
                <div class="card-body">
                    <h5 class="card-title">@item.Name</h5>
                    <p class="card-text">@item.Desription</p>
                    @{
                        if (item.Reports!=null)
            {
                <p class="card-text">@item.Reports.Count() reviews</p>
            }
                    }
                    @{
                        if (item.Images!=null)
                        {
                            <p class="card-text">@item.Images.Count() photos</p>
                        }
                    }
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Go to there</a>
                </div>
            </div>
        }
    </div>
}
@if (Model.PageViewModel.HasPreviousPage)
{
    <a asp-controller="Places"
       asp-action="Index"
       asp-route-pageNum="@(Model.PageViewModel.PageNumber - 1)"
       class="btn btn-default btn">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Назад
    </a>
}

@if (Model.PageViewModel.HasNextPage)

{
    <a asp-controller="Places"
       asp-action="Index"
       asp-route-pageNum="@(Model.PageViewModel.PageNumber + 1)"
       class="btn btn-default btn">
        Вперед
        <i class="glyphicon glyphicon-chevron-right"></i>
    </a>

}